const actions = {
    FETCH_APPLIANCE_LIST : 'FETCH_APPLIANCE_LIST',
    FETCH_APPLIANCE_LIST_SUCCESS: 'FETCH_APPLIANCE_LIST_SUCCESS',
    FETCH_APPLIANCE_LIST_FAILED: 'FETCH_APPLIANCE_LIST_FAILED',
    FETCH_SELECTED_APPLIANCE_INFO : 'FETCH_SELECTED_APPLIANCE_INFO',
    FETCH_SELECTED_APPLIANCE_INFO_SUCCESS: 'FETCH_SELECTED_APPLIANCE_INFO_SUCCESS',
    FETCH_SELECTED_APPLIANCE_INFO_FAILED: 'FETCH_SELECTED_APPLIANCE_INFO_FAILED',
    SET_ROW_COUNT: 'SET_ROW_COUNT',
    SET_TABLE_SEARCH_VALUE: 'SET_TABLE_SEARCH_VALUE',
    SET_TABLE_PAGINATION_VALUE: 'SET_TABLE_PAGINATION_VALUE',
}

export default actions;